# This is a basic workflow to help you get started with Actions

name: Publish to npm

on: 
  workflow_dispatch:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
      - uses: ericcornelissen/git-tag-annotation-action@v1
        id: tagMessage
      - name: Tag name
        run : echo ${{ steps.tagName.outputs.tag }} ${{ steps.tagMessage.outputs.git-tag-annotation }}
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.3.7
        with: # All of theses inputs are optional
          tag_name: ${{ steps.tagName.outputs.tag }}
          tag_message: ${{ steps.tagMessage.outputs.git-tag-annotation }}
          create_tag: "true"
          commit_pattern: "^Release (\\S+)"
          workspace: "."
          publish_command: "npm"
          publish_args: "--non-interactive"
        env: # More info about the environment variables in the README
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # You need to set this in your repo settings
